<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>AnyConv.com__logotest.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UI\Resources\Images\background.png" />
    <None Remove="UI\Resources\Images\camera.png" />
    <None Remove="UI\Resources\Images\camera原.PNG" />
    <None Remove="UI\Resources\Images\logo - 100x84.png" />
    <None Remove="UI\Resources\Images\logo.png" />
    <None Remove="UI\Resources\Images\poster-04.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AnyConv.com__logotest.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Tools\" />
    <Folder Include="Tools\RtspQuickDiagnostic\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EPPlus" Version="8.0.5" />
    <PackageReference Include="LibVLCSharp" Version="3.9.7.1" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.7.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.5" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
    <PackageReference Include="System.Speech" Version="9.0.6" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UI\Resources\Images\background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Resources\Images\camera.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Resources\Images\camera原.PNG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Resources\Images\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Resources\Images\poster-04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="導出模板\CP08-003-02版-產品測試記錄表.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\start_music.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\stop_music.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
